# Generated by Django 2.2.4 on 2019-08-28 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Poets',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('p_id', models.IntegerField()),
                ('name', models.CharField(max_length=50)),
                ('pic', models.CharField(max_length=50)),
                ('link', models.CharField(max_length=50)),
                ('biography', models.TextField()),
            ],
        ),
    ]
